containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "standard"
    resources:
      requests:
        storage: 1Gi
  kubernetesModeServiceAccountName: "default"

template:
  spec:
    securityContext:
      fsGroup: 123