template:
  spec:
    containers:
      - name: runner
        image: asia-northeast1-docker.pkg.dev/project-b8ee474a-9624-49ce-b08/alphabetbengali/runner:latest
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
