name: Test (handlers)

on:
  push:
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: go-test
    steps:
      - uses: actions/checkout@v6

      - name: Test
        working-directory: backend
        run: go test ./handlers/...
