name: Test (data)

on:
  push:
    paths:
      - 'backend/data/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        working-directory: backend
        run: docker build --target builder -t test-image .

      - name: Test
        run: docker run --rm test-image go test ./data/...
