name: Test (models)

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: go-test
    container:
      image: golang:1.26.2
      options: --user root
    steps:
      - uses: actions/checkout@v6

      - name: Test
        working-directory: backend
        run: go test ./models/...
